
Flowpack:
  SingleSignOn:
    DemoServer:
      demoInstanceUri: ''
      clients: null
Neos:
  Flow:
    security:
      authentication:
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: WebRedirect
            entryPointOptions:
              uri: login
